#!/bin/bash
if [[ -e /tmp/community.applications/tempFiles/appdata/inprogress ]]
then
  logger "Community Applications Calculations of Appdata in progress"
  PID=`cat /tmp/community.applications/tempFiles/appdata/inprogress`
  logger "Terminating $PID"
  kill $PID
fi
if [[ -e /tmp/community.applications/tempFiles/backupInProgress ]]
then
  logger "Community Applications Backup / Restore of Appdata in progress"
  PID=`cat /tmp/community.applications/tempFiles/backupInProgress`
  logger "Terminating $PID"
  kill $PID
fi
